#!/usr/bin/env bash

set -e

export $(cat $HOME/envs/wallpaper.env | xargs)

SECRETS_PATH="$HOME/.wallpaper.json"

echo "$CREDENTIALS" > "$SECRETS_PATH"

"$GPHOTOS_COMMAND_PATH" \
    --album "Wallpaper" \
    --use-hardlinks \
    --omit-album-date \
    --skip-video \
    --secret "$SECRETS_PATH" \
    --use-flat-path \
    "$STORAGE_PATH"
