#!/usr/bin/env bash

set -e

SECRETS_PATH="$HOME/.wallpaper.json"

echo "$CREDENTIALS" > "$SECRETS_PATH"

gphotos-sync \
    --album "Wallpaper" \
    --use-hardlinks \
    --omit-album-date \
    --skip-video \
    --secret "$SECRETS_PATH" \
    --use-flat-path \
    "$STORAGE_PATH"
