apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync
  namespace: wallpaper
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsGroup: 1001
            runAsUser: 1026
          volumes:
          - name: secrets
            emptyDir:
              medium: Memory
          - name: storage
            nfs:
              path: /volume1/farm/wallpaper
              server: nas.local
          initContainers:
          - name: secretboi
            image: arecker/secretboi:latest
            volumeMounts:
            - name: secrets
              mountPath: /secrets
            env:
            - name: VAULT_ADDR
              value: http://vault.vault.svc.cluster:8200
            - name: VAULT_ROLE
              value: wallpaper
            - name: ONLY_RUN_ONCE
              value: "true"
            - name: SECRET_wallpaper.json
              value: /wallpaper
          containers:
          - name: sync
            image: arecker/wallpaper-sync:latest
            command: [ "gphotos-sync" ]
            args: ["--album", "Wallpaper",  "--use-hardlinks", "--omit-album-date", "--skip-video",  "--secret", "/secrets/wallpaper.json", "--use-flat-path",  "/storage" ]
            volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
            - name: storage
              mountPath: /storage
