apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: wallpaper
spec:
  replicas: 3
  selector:
    matchLabels:
      name: proxy
  template:
    metadata:
      labels:
        name: proxy
    spec:
      volumes:
        - name: storage
          nfs:
            path: /volume1/farm/wallpaper
            server: nas.local
      containers:
      - name: proxy
        image: arecker/wallpaper-proxy:latest
        volumeMounts:
        - name: storage
          mountPath: /storage
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: wallpaper
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    name: proxy
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: proxy
  namespace: wallpaper
spec:
  rules:
  - host: wallpaper.local
    http:
      paths:
      - backend:
          serviceName: proxy
          servicePort: 80
