name: Master

on:
  push:
    branches: master

jobs:
  Merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      - uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - run: ./dockerBuild.sh
